/**
 * Tools
 */
const HIDE_SAVE_FORM_TOOL = 'DEALER_ORDER_FORM_HIDE_SAVE_FORM_TOOL'
const SHOW_SAVE_FORM_TOOL = 'DEALER_ORDER_FORM_SHOW_SAVE_FORM_TOOL'
const SET_STATE_SAVE_FORM_TOOL = 'SDEALER_ORDER_FORM_ET_STATE_SAVE_FORM_TOOL'

const HIDE_LOAD_FORM_TOOL = 'DEALER_ORDER_FORM_HIDE_LOAD_FORM_TOOL'
const SHOW_LOAD_FORM_TOOL = 'DEALER_ORDER_FORM_SHOW_LOAD_FORM_TOOL'
const SET_STATE_LOAD_FORM_TOOL = 'DEALER_ORDER_FORM_SET_STATE_LOAD_FORM_TOOL'

const HIDE_CHANGE_FORM_TOOL = 'DEALER_ORDER_FORM_HIDE_CHANGE_FORM_TOOL'
const SHOW_CHANGE_FORM_TOOL = 'DEALER_ORDER_FORM_SHOW_CHANGE_FORM_TOOL'
const SET_STATE_CHANGE_FORM_TOOL = 'DEALER_ORDER_FORM_SET_STATE_CHANGE_FORM_TOOL'

const HIDE_CANCELLATION_REQUEST_FORM_TOOL = 'DEALER_ORDER_FORM_HIDE_CANCELLATION_REQUEST_FORM_TOOL'
const SHOW_CANCELLATION_REQUEST_FORM_TOOL = 'DEALER_ORDER_FORM_SHOW_CANCELLATION_REQUEST_FORM_TOOL'
const SET_STATE_CANCELLATION_REQUEST_FORM_TOOL = 'DEALER_ORDER_FORM_SET_STATE_CANCELLATION_REQUEST_FORM_TOOL'

const SET_STATE_INVENTORY_FORM_TOOL = 'DEALER_ORDER_FORM_SET_STATE_INVENTORY_FORM_TOOL'

const HIDE_ALL_MODAL_FORM_TOOL = 'DEALER_ORDER_FORM_HIDE_ALL_MODAL_FORM_TOOL'
const UPDATE_EXPENSE_TOOL = 'DEALER_ORDER_FORM_UPDATE_EXPENSE_TOOL'

export default {
    HIDE_SAVE_FORM_TOOL,
    SHOW_SAVE_FORM_TOOL,
    SET_STATE_SAVE_FORM_TOOL,

    HIDE_LOAD_FORM_TOOL,
    SHOW_LOAD_FORM_TOOL,
    SET_STATE_LOAD_FORM_TOOL,

    SHOW_CHANGE_FORM_TOOL,
    HIDE_CHANGE_FORM_TOOL,
    SET_STATE_CHANGE_FORM_TOOL,

    SET_STATE_INVENTORY_FORM_TOOL,

    HIDE_ALL_MODAL_FORM_TOOL,

    HIDE_CANCELLATION_REQUEST_FORM_TOOL,
    SHOW_CANCELLATION_REQUEST_FORM_TOOL,
    SET_STATE_CANCELLATION_REQUEST_FORM_TOOL,

    UPDATE_EXPENSE_TOOL
}
